# Generated by Django 2.0.4 on 2018-04-24 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
